spring:
  application:
    name: cloud-file
  datasource:
    url: jdbc:mysql://175.24.205.213:3306/cloud_file?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: username
    password: lmjnb666
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      chat: qwen-max
      api-key: sk-Lf43HULS25rPLbjE2WyId3bfeVYBbLRrLKZVdHxf11fMsOde
      base-url: https://hk.xty.app
      image:
        api-key: sk-Lf43HULS25rPLbjE2WyId3bfeVYBbLRrLKZVdHxf11fMsOde
        base-url: https://hk.xty.app
      audio:
        speech:
          api-key: sk-Lf43HULS25rPLbjE2WyId3bfeVYBbLRrLKZVdHxf11fMsOde
          base-url: https://hk.xty.app
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8085
  servlet:
    session:
      timeout: PT876000H